### ISSUE TITLE
Not update files in fs after error

### ISSUE THREAD

**Issue by jaybekster** [shama/webpack-stream#101]
When webpack retruns an error in stats object it does't write actual files changes after it's fixed.
Althought webpack is watching files by itslef and compile it withoud errors after fixing it returns some kind of MemoryFileSystem object and on the next handler doesn't write.

This handler doesn't trigger.
```javascript
.pipe(gulp.dest(<some path>));

**Comment by jaybekster** [comment]
I resolved this issue isung gulp-plumber. Still don't know how to restart writing changes to files without using its plugin.

**Comment by jeffijoe** [comment]
I think this is a bug, I am having the same issue.

It seems the last version of webpack-stream that worked well was 2.1.0 - downgrading again.
