### ISSUE TITLE
Doesn't watch files on Vagrant

### ISSUE THREAD

**Issue by ihorml** [shama/webpack-stream#103]
If you create vagrant box and start to work with synced directory from your IDE on host and run webpack on gulp on guest files watcher doesn't work and doesn't rebuild app. 

Am using this generator - https://github.com/Swiip/generator-gulp-angular

**Comment by shama** [comment]
Closing as this isn't an issue with this library. Depending on the watcher you're using, you'll likely have to use stat polling with vagrant as the watcher that gulp and webpack use, uses native events which don't work across vagrant shared folders.
