### ISSUE TITLE
Some way to know when webpack end  with watch option enabled?

### ISSUE THREAD

**Issue by gbahamondez** [shama/webpack-stream#105]
I need to know  when my webpack task ends and it start to watch the files change, i tried by this way, without success.

```javascript
gulp.task("pack", function() {
  var stream = webpack({
    output : {
      filename : "bundle.js"
    },
    watch  : true
  });

  stream.on("end", function() {
    console.log("build end!");
  });

  return gulp.src("public/src/app/app.js").pipe(stream)
    .pipe( gulp.dest("public/dist"));
});
```

When i run the task with gulp pack command, webpack start to watch but never emits the "end" event, instead of that, when i remove the watch option or set it to false, the "end" event is triggered as well.

There is some way to know when webpack start listen for changes,  using watch = true?

**Comment by shama** [comment]
Is this the same issue as https://github.com/shama/webpack-stream/issues/18? I don't use the `watch` flag with webpack and gulp so I don't know.

**Comment by gbahamondez** [comment]
@shama  i think [#18](https://github.com/shama/webpack-stream/issues/18) is more about not working watch option, but currently  for me  that is working fine, my problem is more about how to know when the webpack task,  in order to trigger some other gulp task to open the browser (gulp-open).

How  you perform this kind of things , without using webpack watch option?

Maybe i should  just use gulp-watch instead  webpack watch option and trigger the webpack task without watch,  each time the files change.

**Comment by shama** [comment]
As long as webpack runs in the same process, running it subsequent times will do incremental builds. So I assumed the `watch` option was for use without another watching library.

You might trying passing an optional callback to `webpack(config, null, callback)` to know when it has compiled. It doesn't end the stream on purpose with `watch: true` specified. That behavior was added in this PR https://github.com/shama/webpack-stream/pull/4, it looks purposeful but I can't say why as I'm not a consumer of that use case.

**Comment by gbahamondez** [comment]
@shama the callback solve my problem, thanks a lot!

**Comment by wphampton** [comment]
Maybe this will help one other poor soul.  For my use I finally got this working relying on the native webpack _watch_ (specified in the webpack config) and not using gulp.watch() calls to monitor my .js source files.  The key for me was calling the gulp "task completed callback" _cb()_ on only the first task iteration (tracked with _taskNum_ variable) within the stats/done webpack callback.

Also below are pieces to load in the external webpack config, adding webpack _watch_ mode if NODE_ENV = development.  Also _webpackStatsConfig_ can be changed to get [different output options](https://github.com/webpack/docs/wiki/node.js-api#statstojsonoptions).  Also a version that does not use webpack-stream that helped me get to a little better understanding of what was happening...though I'm not sure which is "better".

```
var gulp = require('gulp');
var webpack = require('webpack');
var webpackStream = require('webpack-stream');
var gutil = require('gulp-util');

gulp.task('webpack', function(cb) {
    var configFile = 'path/to/webpack/config.js';
    var configFileContent = require(configFile);
    var addConfig = {
        watch: process.env.NODE_ENV === 'development' ? true : false
    };
    var finalConfig = Object.assign({}, configFileContent, addConfig);
    var webpackStatsConfig = {
        colors: true, hash: false, version: false, timings: false, assets: true, chunks: false,
        chunkModules: false, modules: false, children: false, cached: false, reasons: false,
        source: false, errorDetails: false, chunkOrigins: false
        //context: '', modulesSort: '', chunksSort: '', assetsSort: ''
    };
    var taskNum = 1; // A counter to track how many times the webpack task runs

    // The block below uses webpack-stream
    return gulp.src('path/to/entry/index.js')
        .pipe(webpackStream(finalConfig, webpack, function(err, stats) {
            var title = 'webpack' + ' compile #' + taskNum + ':\r\n';

            gutil.log(title, stats.toString(webpackStatsConfig));

            // Only execute this callback the first time
            if (taskNum === 1) {
                cb();
            }

            taskNum++; // Increment the task counter
        }))
        .pipe(gulp.dest('path/to/dest/directory'));
    // End webpack-stream version

    // The block below does not require webpack-stream (not sure about pros or cons)
    /*webpack(finalConfig, function(err, stats) {
        var title = 'webpack' + ' compile #' + taskNum + ':\r\n';

        if(err) throw new gutil.PluginError("webpack", err);
        gutil.log(title, stats.toString(webpackStatsConfig));
        gutil.log('webpack is watching for changes...');

        // Only execute this callback the first time
        if (taskNum === 1) {
            cb();
        }

        taskNum++; // Increment the task counter
    });*/
    // End native webpack version
});
```

**Comment by abjrcode** [comment]
@wphampton Thanks for your response. Indeed I was able to make it work **only** when relying on `webpack.watch` api.

**Comment by dlebedynskyi** [comment]
had to use something simmilar 
```
const webpack = require('webpack');

gulp.task('watch:src', (cb) => {
	const config = Object.create(require('../../webpack.config.js'));
	config.watch = true;
	config.cache = true;
	config.debug = true;
	config.bail = false;

	webpack(config, function(error, stats) {
		if (error) {
			gutil.log('[webpack]', error);
		}
		showSummary(stats);
	});
});

function showSummary(stats) {
	gutil.log('[webpack]', stats.toString({
		colors: gutil.colors.supportsColor,
		hash: false,
		timings: false,
		chunks: false,
		chunkModules: false,
		modules: false,
		children: true,
		version: true,
		cached: false,
		cachedAssets: false,
		reasons: false,
		source: false,
		errorDetails: false
	}));
}
```

webpack-stream watch does not really work and was noted some long time ago
