### ISSUE TITLE
Loaders not working

### ISSUE THREAD

**Issue by jscheel** [shama/webpack-stream#107]
I have a loader set like so:
```
loaders: [
    { test: /\.css$/, loader: "style!css" }
],
```
but, it will not work automatically. I have to specify the loaders in my require to get anything to work.

**Comment by shama** [comment]
`loaders` needs to be under the `module` key:

```js
module: {
  loaders: []
}
```

https://webpack.github.io/docs/using-loaders.html#configuration

**Comment by jscheel** [comment]
Yep, I'm a special kind of stupid. Thanks.
