### ISSUE TITLE
How do I specify production build

### ISSUE THREAD

**Issue by medreda** [shama/webpack-stream#111]
Hi everyone,

My question may be simple. I'm wondering how I can specify to webpack that I'm building for production.

Using webpack on the command line I can using `webpack -p` option. On the other hand, I couldn't find any option that enables it from the [webpack config object](https://webpack.github.io/docs/configuration.html).

P.S : Is it recommended to have 2 webpack config files for dev & production ( I've seen some projects like this ) or is there a simpler method ?

Thanks :)

**Comment by shama** [comment]
This question would be better asked on a webpack support channel as it doesn't relate to an issue with this library. Thanks!
