### ISSUE TITLE
[question] mutiple entry points

### ISSUE THREAD

**Issue by ianwith** [shama/webpack-stream#112]
let's say we have
```js
var gulp = require('gulp');
var webpack = require('webpack-stream');
gulp.task('default', function() {
  return gulp.src('src/entry.js')
    .pipe(webpack({
      entry: {
        app: 'src/app.js',
        test: 'test/test.js',
      },
      output: {
        filename: '[name].js',
      },
    }))
    .pipe(gulp.dest('dist/'));
});
```

It appears that entries will be 'src/app.js', 'test/test.js'. However, I actually want 'src/entry.js' to be one of the entries.
Why can't we concat the 'src/entry' with webpack config entry? It will be useful when we define vendor code like `vendor: ["jquery", "underscore", ...]`

**Comment by ianwith** [comment]
@shama

**Comment by shama** [comment]
You can either provide entry files via `gulp.src()` or through the `entry` in webpack config, but not both.

**Comment by ianwith** [comment]
So, I can specify any file in gulp.src(), and this has nothing to do with my webpack entry config and is no use in the pipelines?
Am I understanding right?
@shama

**Comment by shama** [comment]
@ianwith Sorry I dont understand your question.

**Comment by danwad** [comment]
@shama, I think @ianwith's question was with regards to the sample in the readme.

```
var gulp = require('gulp');
var webpack = require('webpack-stream');
gulp.task('default', function() {
  return gulp.src('src/entry.js')
    .pipe(webpack({
      entry: {
        app: 'src/app.js',
        test: 'test/test.js',
      },
      output: {
        filename: '[name].js',
      },
    }))
    .pipe(gulp.dest('dist/'));
});
```

What is the significance of `gulp.src('src/entry.js')` while the entry property is set in the config?

Could `src/entry.js` be anything? Does the file have to exist on the filesystem?

**Comment by fclaussen** [comment]
I have the exact same question. Does entry.js need to exist?
