### ISSUE TITLE
Issue importing `gcloud-node` module

### ISSUE THREAD

**Issue by zackharley** [shama/webpack-stream#120]
I've created a JavaScript module that is attempting to import `gcloud-node`. I've tried importing with both ES5 and ES2015 syntax and it's not changing the result. The original error I was getting was saying that I needed a new loader for JSON files, so I added `json-loader`. Now I'm getting an error telling me that there are unexpected characters in dependencies of `gcloud-node` and that some of the dependencies don't exist.

I've tried reinstalling all of the packages and that didn't help. I've also created a stripped down file that only imports `gcloud-node` and that doesn't work:
*index.js*
```
import gcloud from 'gcloud-node';
// or 
var gcloud = require('gcloud-node');
```

Has anyone run into a similar issue?

**Comment by shama** [comment]
Closing as I dont think this is an issue related to `webpack-stream`. Nor am I familiar with what `gcloud-node` is.
