### ISSUE TITLE
When used with gulp watch all js files are being rebuilt

### ISSUE THREAD

**Issue by aventic** [shama/webpack-stream#122]
When webpack-stream is used in a gulp watch task it rebuilds all files, resulting in slow compile time.

This is my gulpfile with all webpack settings within:

```
var gulp = require('gulp'),
	util = require('gulp-util'),
	sass = require('gulp-sass'),
	webpack = require('webpack');
	webpackStream = require('webpack-stream');

gulp.task('webpack', function () {
	return gulp.src('./build/scripts/entry.js')
		.pipe(webpackStream({
			entry: './build/scripts/entry.js',
			output: {
				path: __dirname + '/public/scripts',
				filename: 'bundle.js'
			},
			resolve: {
				extensions: ['', '.webpack.js', '.web.js', '.js', '.ts']
			}
		}, webpack, function (err, stats) {
			console.log(stats.toString({ colors: true }));
		}))
		.pipe(gulp.dest('./public/scripts'));
});

gulp.task('scss', function () {
	return gulp.src('./build/styles/**/*.scss')
		.pipe(sass())
		.pipe(gulp.dest('./public/styles'));
});

gulp.task('watch', function () {
	gulp.watch('./build/scripts/**/*.js', ['webpack']);
	gulp.watch('./build/styles/**/*.scss', ['scss']);
});
```

If I just use webpack --watch, only the edited file will be rebuilt, not working with above gulp webpack-stream.

**Comment by jswny** [comment]
In your Webpack config you can specify `watch: true` like this:
```
gulp.task('webpack', function () {
    return gulp.src('./build/scripts/entry.js')
        .pipe(webpackStream({
            watch: true,
            entry: './build/scripts/entry.js',
            output: {
                path: __dirname + '/public/scripts',
                filename: 'bundle.js'
            },
            resolve: {
                extensions: ['', '.webpack.js', '.web.js', '.js', '.ts']
            }
        }, webpack, function (err, stats) {
            console.log(stats.toString({ colors: true }));
        }))
        .pipe(gulp.dest('./public/scripts'));
});
```

That way, Webpack will watch the files and only rebuild the ones that have been changed instead of Gulp watching the files and re-running the entire `webpack` task.

**Comment by aventic** [comment]
@jswny what if I simply want to build my javascript, not watching. For example running mulitple tasks.

**Comment by jswny** [comment]
@aventic So you want the `webpack` task to run only once? I'm confused as to what you are asking. If you could elaborate more maybe I could better help you.

**Comment by aventic** [comment]
@jswny If I run my task `webpack` it will build my files, if I add `watch: true` I cant run multiple task etc: `gulp.task('build', ['webpack', 'styles']);`. It will still be in watch mode and not execute following tasks. Makes sense?

But I found a way, if I do a simple gulp watch and watch my files instead of adding `watch: true` I will achieve what I want. Just got confused by the whole, where to watch as the readme had an example to use it inside my webpack config.

**Comment by jswny** [comment]
@aventic Ah ok, I understand now. I experimented with the same thing because when using Gulp to watch the files it recompiles everything every time any file is changed. If you want to try letting Webpack watch the files while still being able to run multiple Gulp tasks you could try removing the `return` from your `webpack` task like so:

```
gulp.task('webpack', function () {
    gulp.src('./build/scripts/entry.js')
        .pipe(webpackStream({
            watch: true,
            entry: './build/scripts/entry.js',
            output: {
                path: __dirname + '/public/scripts',
                filename: 'bundle.js'
            },
            resolve: {
                extensions: ['', '.webpack.js', '.web.js', '.js', '.ts']
            }
        }, webpack, function (err, stats) {
            console.log(stats.toString({ colors: true }));
        }))
        .pipe(gulp.dest('./public/scripts'));
});
```

However, this may conflict with other tasks that watch files such as `gulp-nodemon`.

**Comment by aventic** [comment]
@jswny Actually I just ended up doing this as my watch:

```
gulp.task('watch', function () {
	gulp.watch(config.init('scripts', 'dev') + '/**/*.ts', ['scripts']);
	gulp.watch(config.init('styles', 'dev') + '/**/*.scss', ['styles']);
});
```

And added this ``watch: util.env._[0] === 'watch'`` inside my webpack config (with gulp util to detect if I'm using my webpack-task from the watch task). Still returning my all my tasks.

**Comment by jswny** [comment]
@aventic Glad it worked out for you! If it's all fixed you should close the issue :)

**Comment by aventic** [comment]
I dont know if it's fixed, definitely required some workaround and alot of fiddle. I'm closing for now, hopefully others who end in my struggle can learn from this :)
