### ISSUE TITLE
please update webpack@2.x.x

### ISSUE THREAD

**Issue by MeCKodo** [shama/webpack-stream#125]
i want use tree-shaking！

**Comment by arobbins** [comment]
Any idea when this will be updated? Would love this as-well.

**Comment by xtianus79** [comment]
@MeCKodo @arobbins 

I am looking into using the webpack angular2 starter pack.  Have you guys looked into using those?  If so, or whatever, what would be wrong with incorporating gulp or grunt into those starter kits?  from what i see this is just using grunt or gulp to kick off those commands

**Comment by dcholth** [comment]
One suggestion would be to switch to using gulp-shell and execute it directly.  This turned out to be a very easy switch for us because we weren't really able to take advantage of the things with gulp we wanted because of issue #72 anyway.

**Comment by GuillaumeLeclerc** [comment]
You can solve that by installing webpack 2 in your package and then doing: 

```javascript
gulp.src('FILES').pipe(webpack(config, require('webpack')))
```

**Comment by saponifi3d** [comment]
This should probably also make webpack a `peerDependency` instead, so end users can control the version of webpack and pin this within a specific range.

**Comment by xtianus79** [comment]
@GuillaumeLeclerc so with webpack 2 you can use / call grunt/gulp commands from within webpack?  if so I am going to be so happy!!!

**Comment by GuillaumeLeclerc** [comment]
@xtianus79 No it's the other way arround. Start webpack2 in gulp.

In my example I show you how to use `webpack-stream` with the version of webpack you want. In my example I require webpack and in my package.json I have the version 2.1.0.beta27. And webpack-stream uses it instead of the one he bundles (1.3 something if I remember well)

**Comment by zwacky** [comment]
I'm also on board with @saponifi3d to use `peerDependencies`.

for a comparison, grunt's webpack uses this:

```
"peerDependencies": {
    "webpack": "^2.1.0-beta || ^2.2.0-rc || ^2.0.0"
}
```

**Comment by sebworks** [comment]
The @GuillaumeLeclerc solution works well.  I'm using the following setup:

```
var handleErrors = require( '../utils/handle-errors' );
var webpack = require( 'webpack' );
var webpackConfig = require( '../../config/webpack-config.js' );
var webpackStream = require( 'webpack-stream' );

/**
 * Standardize webpack workflow for handling script
 * configuration, source, and destination settings.
 * @param {Object} config - Settings for webpack.
 * @param {string} src - Source URL in the unprocessed assets directory.
 * @param {string} dest - Destination URL in the processed assets directory.
 * @returns {PassThrough} A source stream.
 */
function _processScript( config, src, dest ) {
  return gulp.src( paths.unprocessed + src )
    .pipe( webpackStream( webpackConfig, webpack ) )
    .on( 'error', handleErrors )
    .pipe( gulp.dest( paths.processed + dest ) )
    .pipe( browserSync.reload( {
      stream: true
    } ) );
}
```

**Comment by zaguini** [comment]
I love you so much, @GuillaumeLeclerc . Thank you!!!
