### ISSUE TITLE
Error while using a webpack.config with a output.path configured

### ISSUE THREAD

**Issue by YoannBureau** [shama/webpack-stream#128]
Hi,

I' trying to re-use my webpack.config file in a gulp task with webpack-stream. My webpackdevserver works fine with this config:

`module.exports = {
    entry: './src/main.js',
    output: {
        path: 'src',
        filename: 'bundle.js'
    },
    devServer: {
        inline: true,
        port: 4444,
        contentBase: 'src'
    },
    module: {
        loaders: [
            {
                test : /\.jsx?/,
                exclude: /node_modules/,
                loader: 'babel'
            }
        ]
    }
}`

And this is my gulp task:
`gulp.task('dist:bundle', function() {
  return gulp.src('./src/main.js')
    .pipe(webpack( require('./webpack.config.js') ))
    .pipe(gulp.dest('dist'));
});`

Unfortunately it throws the following error while trying to execute it:

> stream.js:74
>       throw er; // Unhandled stream error in pipe.
>       ^
> Error: invalid argument
>     at pathToArray (C:\Git\scotch-io\react-routing\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
>     at MemoryFileSystem.mkdirpSync (C:\Git\scotch-io\react-routing\node_modules\memory-fs\lib\MemoryFileSystem.js:139:13)
>     at MemoryFileSystem.(anonymous function) [as mkdirp](C:Gitscotch-ioreact-routingnode_modulesmemory-fslibMemoryFileSystem.js:279:34)
>     at Compiler.<anonymous> (C:\Git\scotch-io\react-routing\node_modules\webpack\lib\Compiler.js:229:25)
>     at Compiler.applyPluginsAsync (C:\Git\scotch-io\react-routing\node_modules\tapable\lib\Tapable.js:60:69)
>     at Compiler.emitAssets (C:\Git\scotch-io\react-routing\node_modules\webpack\lib\Compiler.js:226:7)
>     at Compiler.<anonymous> (C:\Git\scotch-io\react-routing\node_modules\webpack\lib\Compiler.js:184:10)
>     at C:\Git\scotch-io\react-routing\node_modules\webpack\lib\Compiler.js:403:12
>     at Compiler.next (C:\Git\scotch-io\react-routing\node_modules\tapable\lib\Tapable.js:67:11)
>     at Compiler.<anonymous> (C:\Git\scotch-io\react-routing\node_modules\webpack\lib\CachePlugin.js:40:4)

Strange thing is that **it works fine if I remove the output.path prop in the webpack config file**, but of course it breaks my webserver.

Can anyone tell me if it's an issue or if my config file is not correct?

Best regards,
Yoann.

**Comment by rbnlffl** [comment]
1.) You were trying to output your bundled js into your src folder. Not an error per se, but still.
2.) Omit the path in the webpack config while leaving the filename.

Had the same problem just minutes ago.

**Comment by YoannBureau** [comment]
Hi, and thanks for your answer.

Yep, because my app folders are structured like this:

**root**
|-package.json
|-webpack.config.js
|-gulpfile.js
|-**src**
|        |-index.html
|        |-main.js
|-**dist**

All of my sources are in the src folder, I want to start my webpack dev server in the src folder and gulp dist in the dist folder.

In my webpack.config, the devserver node is like this: `
    devServer: {
        port: 4444,
        contentBase: 'src'
    },`

What shoul I put in my webpack.config to allow me to do this?

**Comment by yinone** [comment]
@YoannBureau in fact the problem will happen when you use the webpack.config which the value of output.path is not start with '/' on linux. Maybe you development your app on Mac. And the following function from Memory-fs module described the reason:

```javascript
function pathToArray(path) {
	path = normalize(path);
	var nix = /^\//.test(path);
	if(!nix) {
		if(!/^[A-Za-z]:/.test(path)) {
			throw new MemoryFileSystemError(errors.code.EINVAL, path);
		}
		path = path.replace(/[\\\/]+/g, "\\"); // multi slashs
		path = path.split(/[\\\/]/);
		path[0] = path[0].toUpperCase();
		
	} else {
		path = path.replace(/\/+/g, "/"); // multi slashs
		path = path.substr(1).split("/");
	}
	if(!path[path.length-1]) path.pop();

	console.log(path);
	return path;
}
```
So i think the nix value tell the platform, but the logic is not strict

**Comment by TimothePearce** [comment]
@YoannBureau You should close the issue ;)
