### ISSUE TITLE
"ENOENT: no such file or directory, lstat '/Users/xxx/Library/Caches/Yarn/npm-webpack-stream-3.2.0-d679c2f1f964b5abae4c1f29d5cb695115deec7b'".

### ISSUE THREAD

**Issue by jrean** [shama/webpack-stream#132]
Hi,

Since yarn update to 0.17.0
A simple `yarn install` command produce the following and "breaks everything".

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/xxx/Library/Caches/Yarn/npm-webpack-stream-3.2.0-d679c2f1f964b5abae4c1f29d5cb695115deec7b'".
info If you think this is a bug, please open a bug report with the information provided in "/Volumes/data/code/fashion/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Please help :-)

**Comment by shama** [comment]
> info If you think this is a bug, please open a bug report with the information provided in "/Volumes/data/code/fashion/yarn-error.log".

Please report the issue to yarn instead.

**Comment by jrean** [comment]
Thank you @shama, I did.
I posted her as it may help others. The bug is quite important as it breaks assets compilation.
https://github.com/yarnpkg/yarn/issues/1836
