### ISSUE TITLE
Cannot create property 'colors' on string 'errors-only'

### ISSUE THREAD

**Issue by ImFluffeh** [shama/webpack-stream#148]
`C:\Users\ImFlu\Documents\FullStack\node_modules\webpack-stream\index.js:59
            statsOptions[key] = defaultStatsOptions[key];
                              ^

TypeError: Cannot create property 'colors' on string 'errors-only'
    at C:\Users\ImFlu\Documents\FullStack\node_modules\webpack-stream\index.js:59:31
    at Array.forEach (native)
    at done (C:\Users\ImFlu\Documents\FullStack\node_modules\webpack-stream\index.js:57:42)
    at C:\Users\ImFlu\Documents\FullStack\node_modules\webpack-stream\index.js:147:7
    at C:\Users\ImFlu\Documents\FullStack\node_modules\webpack\lib\Compiler.js:267:15
    at Compiler.emitRecords (C:\Users\ImFlu\Documents\FullStack\node_modules\webpack\lib\Compiler.js:362:37)
    at C:\Users\ImFlu\Documents\FullStack\node_modules\webpack\lib\Compiler.js:260:12
    at C:\Users\ImFlu\Documents\FullStack\node_modules\webpack\lib\Compiler.js:355:11
    at next (C:\Users\ImFlu\Documents\FullStack\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.<anonymous> (C:\Users\ImFlu\Documents\FullStack\node_modules\webpack-stream\index.js:178:9)`

No idea why this is being caused, but running just plain webpack works

**Comment by ImFluffeh** [comment]
I may have fixed it for you. Let me just double-check

**Comment by ImFluffeh** [comment]
Alright mate, I got it working for you.

At the 'options.verbose' check, you were trying to treat a primitive like an object. So, to fix the issue, I did this

`if (options.verbose) {
        gutil.log(stats.toString({
          colors: gutil.colors.supportsColor
        }));
      } else {
        var statsOptions = options && options.stats || {};
        // options && options.stats resulted in 'errors-only' (just a string) for me.
        // Discarding it seems pretty foolish, so I kept the value around and just
        // assigned it to the 'stats' in the table. It seems to have worked fine because
        // I get colored gulp output
        // Do note, I was using the other version of webpack. I'll post a fix for that shortly. 
        if(typeof statsOptions === typeof "") {
          var backup = statsOptions
          statsOptions = undefined
          statsOptions = {}
          statsOptions.stats = backup
        }
        Object.keys(defaultStatsOptions).forEach(function (key) {
            statsOptions[key] = defaultStatsOptions[key]; // offending line
        });

        gutil.log(stats.toString(statsOptions));
      }`

**Comment by ImFluffeh** [comment]
Totally just found my issue. 'errors-only' was something I was using. My bad.

**Comment by tommck** [comment]
I don't think you should ignore this :)  I'm getting is error too


if I set `stats: 'errors-only'` I get this exact error 

```
TypeError: Cannot create property 'colors' on string 'errors-only'
    at .,,\node_modules\webpack-stream\index.js:62:31
```

guess I should open another bug
