### ISSUE TITLE
Updating from 3.2.0 to 4.0.0

### ISSUE THREAD

**Issue by Kamilius** [shama/webpack-stream#162]
Are there any breaking changes while updating from v3.2.0 to v4.0.0 to be aware of?

**Comment by shama** [comment]
webpack went from `1.9.x` to `3.4.x` so unless you're supplying your own version of webpack to this library, expect all those breaking changes that occurred from those: https://webpack.js.org/guides/migrating/

**Comment by Kamilius** [comment]
Thanks @shama
