### ISSUE TITLE
Usage w/o gulp

### ISSUE THREAD

**Issue by ORESoftware** [shama/webpack-stream#166]
@webpack-stream maintainers 

I would like to create a Webpack build that I can stream to the browser, something like this:

```js
app.use(function(req,res,next){
  res.write('<script>');
  res.pipe(webpack(), {end: false});
  res.end('</script>');
});
```

my question is - is there a way to use `webpack-stream` without Gulp? My understand is that Gulp uses `vinyl` streams, so that the above example won't quite work (since vinyl streams don't play well with Node.js core streams). 

Please advise, thanks.

**Comment by shama** [comment]
Just pipe to a through stream that returns the `contents` of the vinyl files. Or listen for the stream to finish and read the contents to give to `res.end`. Or just use webpack directly and call `res.end` when it's API calls the callback.

**Comment by ORESoftware** [comment]
@shama  help me out a little more please

on the front-end, I guess we have:

`<script src="localhost:6969/webpack_build"></script>`

then the server does something like:


```js
app.use('webpack_build',function(req,res,next){
  res.pipe(webpack());
});
```

can you fill in the blanks in the javascript above? sorry I am not quite following.

thanks

**Comment by shama** [comment]
I won't fill in the blanks but I'll point you to some resources to learn how to fill in the blanks ;)

Here is a short video I made on Node streams: https://www.youtube.com/watch?v=yOSNQZm3Trw

This is a great handbook about Node streams: https://github.com/substack/stream-handbook

Or if just using webpack directly, see the webpack docs on using with Node: https://webpack.js.org/api/node/

**Comment by ORESoftware** [comment]
@shama ok bro I love you and I need more help - my goal is to avoid writing the build to the filesystem, I want to stream the build to the browser without writing it to the filesystem, that is my goal, that's one of the upsides of streams.

I am good with streams, that is not a problem...but from what you are telling me, and from what the docs indicate, it's not possible to avoid writing a webpack build to the filesystem? Surely you know the answer to that question?

**Comment by ORESoftware** [comment]
For example, I opened this issue - https://github.com/webpack/webpack/issues/5894

can you answer it?

**Comment by shama** [comment]
Oh if you're familiar with streams then just pipe to a through stream that returns the `contents` of the vinyl files. No file system is involved, only virtual ones.

**Comment by ORESoftware** [comment]
I don't want to take up too much of your time, but I would like to avoid Gulp + Vinyl streams. I'd prefer to just use core Node.js streams..do you know of a way to use Webpack with core Node.js streams?
