### ISSUE TITLE
remove old npm package "gulp-webpack"

### ISSUE THREAD

**Issue by zigszigsdk** [shama/webpack-stream#177]
It seems that https://www.npmjs.com/package/webpack-stream and https://www.npmjs.com/package/gulp-webpack are the same project, except gulp-webpack hasn't been updated for a long time which include updates to webpack itself, such as json-loader being a default loader, which is the only reason i started to look into it.

I don't know what the reason that both exist is, but in order to avoid confusion i recommend closing or if possible redirecting gulp-webpack on npm, just as it is here on github: https://www.github.com/shama/gulp-webpack

Cheers

**Comment by shama** [comment]
I deprecated `gulp-webpack` with a message pointing people here. Thanks!

**Comment by zigszigsdk** [comment]
Sweet!
