### ISSUE TITLE
 Unexpected end of input - npm install --save-dev webpack-stream

### ISSUE THREAD

**Issue by baxri** [shama/webpack-stream#181]
## Issue/Bug

There is a problem in instalation. when I run 

`npm install --save-dev webpack-stream`

it throws exception 

` Unexpected end of input at 1:62026`
`rap":false,"directories":{},"dist":{"integrity":"sha512-tSqlO7/GZHAVS`

![webpack-error](https://user-images.githubusercontent.com/7827156/37243264-047251f8-2490-11e8-843d-6ae1950246eb.png)

## OS info

WIndows 10 
npm -v 5.3.0
node -v 8.5.0

**Comment by shama** [comment]
Looks like an issue with npm: https://github.com/npm/npm/issues/18036

And you can likely solve with `npm cache clean`.

**Comment by baxri** [comment]
It worked, Thanks :)
