### ISSUE TITLE
can't find babel?

### ISSUE THREAD

**Issue by cjdxhjj** [shama/webpack-stream#192]
Error: Entry module not found: Error: Can't resolve 'babel' in 'F:\es\src\frontend'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
resolve 'babel' in 'F:\es\src\frontend'
  Parsed request is a module
  using description file: F:\es\src\frontend\package.json (relative path: .)
  after using description file: F:\es\src\frontend\package.json (relative path: .)
    resolve as module
      F:\es\src\node_modules doesn't exist or is not a directory
      F:\es\node_modules doesn't exist or is not a directory
      F:\node_modules doesn't exist or is not a directory
      looking for modules in F:\es\src\frontend\node_modules
        using description file: F:\es\src\frontend\package.json (relative path: ./node_modules)
        after using description file: F:\es\src\frontend\package.json (relative path: ./node_modules)
          using description file: F:\es\src\frontend\package.json (relative path: ./node_modules/babel)
            no extension
              F:\es\src\frontend\node_modules\babel doesn't exist
            .js
              F:\es\src\frontend\node_modules\babel.js doesn't exist
            .json
              F:\es\src\frontend\node_modules\babel.json doesn't exist
            as directory
              F:\es\src\frontend\node_modules\babel doesn't exist

**Comment by shama** [comment]
`You need to specify 'babel-loader' instead of 'babel'`

Newer versions of webpack require you include the `-loader` part now.
