### ISSUE TITLE
how could i change the mode effectively?

### ISSUE THREAD

**Issue by jeffery5461** [shama/webpack-stream#196]
Hi!
i wanna use 'production' mode in webpack-stream to change the setting in my webpack.config whose mode there is 'development'. i've tried it with this, but it no works cause the js in the dist is not compressed. By the way, i use the webpack4.

gulp.task('default', function () {

    return gulp.src('src/index.js')

    .pipe(webpack({

      mode: 'production', // no works here

      devtool: 'null',

      config: require('./webpack.config'),

    }))

    .pipe(gulp.dest('dist'));

});

here's my webpack.config.js assuming it is needed.

module.exports = {

    watch: true,

    mode: 'development',

    devtool: "eval-source-map",

    module: {
      ......
    },

    plugins: [

      new miniCssExtractPlugin({

        filename: 'index.[hash:8].css'

      })

    ]

};

**Comment by shama** [comment]
Override it in your config:
```js
const config = require('./webpack.config')
config.mode = 'production'
// ...
.pipe(webpack({
  config: config
}))
```
