### ISSUE TITLE
'watch' is not watching

### ISSUE THREAD

**Issue by kehator** [shama/webpack-stream#199]
Since version 5.0.0, when gulp starts a task, webpack is starting as usual, saying it's watching for a changes, but whenever the file is changed, the webpack does nothing like not detecting any changes. 4.03 works fine. Passing different versions of webpack is not making any difference.

**Comment by shama** [comment]
I recommend searching this issue tracker or git history for the individuals who added the dual watch thing and ping them to ask. Or get real specific with a repro of the issue as it relates to this library as I don't use gulp.

**Comment by strunkie30** [comment]
Same issue here.

**Comment by shama** [comment]
I recommend searching this issue tracker or git history for the individuals who added the dual watch thing and ping them to ask. Or get real specific with a repro of the issue as it relates to this library as I don't use gulp.

**Comment by mrG0bliN** [comment]
@shama i think its double post   😢

**Comment by shama** [comment]
Sometimes I repost comments if I don't think they are being read.

**Comment by kehator** [comment]
I thought that this first post of yours @shama was stupid.. but that last one just shows how retarded you are

**Comment by shama** [comment]
Thank you for me writing free code for you so enjoyable!
