### ISSUE TITLE
`pipe(gulp(dest))` actually works?

### ISSUE THREAD

**Issue by stoplion** [shama/webpack-stream#217]
Unless I'm misunderstanding,
when running...
```
gulp.task('default', function() {
  return gulp.src('src/entry.js')
    .pipe(webpack())
    .pipe(gulp.dest('foobar/'));
});

```
a javascript file will never make to the dir `foobar`.

It just drops it in the `dist`, regardless of what `gulp.dest` you set.

Is this correct?

The destination is actually set in the webpack config and never the `pipe(gulp(dest))` ?

**Comment by robchristian** [comment]
+1 on this. Not holding my breath about getting a response. Been almost 5 months and there's no reply to this issue.

**Comment by Backfighter** [comment]
Looking at the source code suggested that using dest() should actually work.
Webpack-stream uses a virtual filesystem for webpack, so unless you pipe the output into dest it will not write any files to disk at all.

**Comment by navanshu** [comment]
Pass configs to your build maybe like this. The output directive is important.
```javascript
.pipe(webpack({
        mode: "production",
        output: {
            filename: 'lazysizes.js',
          },
    }))
```
