### ISSUE TITLE
DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead

### ISSUE THREAD

**Issue by illiakovalenko** [shama/webpack-stream#222]
`(node:24932) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.`

Using this code:

`var stream = gulp.src(streamSource).pipe(webpack({ mode: 'production', stats: 'none' }))`

can you look at this problem?

npm 6.11.13
node v10.16.3
gulp Local version: 4.02
gulp CLI version: 2.2.0

**Comment by shama** [comment]
Duplicate of https://github.com/shama/webpack-stream/issues/221
