### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by franktopel** [shama/webpack-stream#227]
On October 11th, Webpack 5 has officially been released.

When will webpack-stream make the switch to that new major version?

**Comment by shama** [comment]
You can supply whatever version of webpack you want (check the readme). This will switch to webpack 5 when someone sends a tested PR for it or whenever I get around to it.

**Comment by franktopel** [comment]
Unfortunately, given our setup switching to webpack 5 is not as easy as simply following the readme. I do not get any build errors or warnings using webpack 5, but I don't get any resulting files either.

**Comment by franktopel** [comment]
Any ideas as of why files are not being output at the configured destination paths via `gulp.dest()`?

**Comment by franktopel** [comment]
We still have no solution for this.

**Comment by shama** [comment]
@franktopel Let us know if you find a solution. Thanks!

**Comment by franktopel** [comment]
Thank you so much for your time and help. Not.

**Comment by shama** [comment]
@franktopel You are welcome! Some people think open source maintainers are obligated to provide free support in addition to the free code they've already given. I'm glad you're not one of those people and are appreciative of the free code I've already given you.
