### ISSUE TITLE
Handle sourcemaps

### ISSUE THREAD

**Issue by kirill-konshin** [shama/webpack-stream#40]
```js
self.queue(new File({
    base: compiler.outputPath,
    path: path,
    contents: contents,
}));
```

Plugin should also read sourcemap and attach it by using, for example `vinyl-sourcemaps-apply` package.

**Comment by Zolmeister** [comment]
+1

**Comment by filipstachura** [comment]
+1

**Comment by monkeymonk** [comment]
+1

**Comment by Siedrix** [comment]
+1

**Comment by sotoer** [comment]
+1

**Comment by shama** [comment]
Has anyone looked into this yet? It might already just work. Instead of +1ing it might be better to look into it and at least post your findings on what you've tried. Thanks!

**Comment by sotoer** [comment]
It doesn't seem like it's supported yet. I ended up using gulp-webserver to proxy to webpack-dev-server.

**Comment by skyrpex** [comment]
@shama, I created this [repo](https://github.com/skyrpex/gulp-webpack-sourcemaps)... it works with sourcemaps, at least for me!

**Comment by shama** [comment]
@skyrpex Nice! Thanks for sharing that! I'll have look.

**Comment by OliverJAsh** [comment]
I have raised a PR to add support at https://github.com/shama/webpack-stream/pull/84/files
