### ISSUE TITLE
npm install dosen't work

### ISSUE THREAD

**Issue by blackpost38** [shama/webpack-stream#70]
I tried to install webpack-stream. But I was refused to install... 
What I to do?

```
npm install webpack-stream 
npm WARN package.json webpack-stream@1.0.0 No description
npm WARN package.json webpack-stream@1.0.0 No repository field.
npm WARN package.json webpack-stream@1.0.0 No README data
npm WARN install Refusing to install webpack-stream as a dependency of itself
```

**Comment by shama** [comment]
It sounds like your `package.json` `name` field contains `webpack-stream`. So npm thinks you're installing a dependency of itself. Please change the name of your package to something else.

**Comment by blackpost38** [comment]
Oh, You're right! Thanks @shama :+1:
