### ISSUE TITLE
On npm it says "increase" instead of decrease.

### ISSUE THREAD

**Issue by anthony-dandrea** [shama/webpack-stream#77]
https://www.npmjs.com/package/gulp-webpack 
"You can pass webpack options in with the first argument, including watch which will greatly *increase* compilation times:"
instead of
"You can pass webpack options in with the first argument, including watch which will greatly *decrease* compilation times:"

The inconsistency confused me a bit.

**Comment by shama** [comment]
Fixed in the last publish, thanks!
