### ISSUE TITLE
can not find the source map file when use UglifyJsPlugin

### ISSUE THREAD

**Issue by plantain-00** [shama/webpack-stream#81]
```
gulp.task('test', function() {
    gulp.src('frontends/scripts/index.js')
        .pipe(webpack({
            plugins: [
                new webpack.webpack.optimize.UglifyJsPlugin({ minimize: true, sourceMap: true })
            ]
        }))
        .pipe(rename("index.min.js"))
        .pipe(gulp.dest('frontends/build/scripts/'));
});
```
The `index.min.js` is created and minified properly, but I can not find any source map file.
And there is no `//# sourceMappingURL=index.min.map` at the end of `index.min.js` file.
Considering [UglifyJsPlugin](http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin) does have `sourceMap` option, is this a bug of `webpack-stream`?

**Comment by shama** [comment]
webpack will output multiple destination files. Are you sure `.pipe(rename("index.min.js"))` isn't just renaming both of the output files to `index.min.js` by mistake?

**Comment by plantain-00** [comment]
@shama `rename` does not change this situation:
```
gulp.task('test', function() {
    gulp.src('frontends/scripts/index.js')
        .pipe(webpack({
            plugins: [
                new webpack.webpack.optimize.UglifyJsPlugin({ minimize: true, sourceMap: true })
            ]
        }))
        //.pipe(rename("index.min.js"))
        .pipe(gulp.dest('frontends/build/scripts/'));
});
```
There is only one file named `10fedf2665417c01a8c3.js`, minified properly, no source map file, no `//# sourceMappingURL=XXXX.map` in `10fedf2665417c01a8c3.js`.

**Comment by shama** [comment]
@plantain-00 Try using webpack's source map setting instead:

```js
.pipe(webpack({
  plugins: [
    new webpack.webpack.optimize.UglifyJsPlugin({ minimize: true })
  ],
  devtool: 'source-map'
}))
```

Here are docs on more options with webpack's `devtool`: https://webpack.github.io/docs/configuration.html#devtool

**Comment by plantain-00** [comment]
@shama it works, thanks.

**Comment by bennyn** [comment]
Using `webpack 2.1.0-beta.21`, I needed to set `sourceMap: true` on `webpack.optimize.UglifyJsPlugin` **AND** `devtool: 'source-map'`.

So in the end my configuration looked like this:

**webpack.config.js**

```javascript
var webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: {
    filename: './build/proteus.js'
  },
  output: {
    filename: 'proteus-bundle.js',
    library: 'proteus',
    libraryTarget: 'amd',
    path: './dist'
  },
  node: {
    fs: 'empty',
    crypto: 'empty'
  },
  externals: {
    'libsodium-native': 'libsodium_native'
  },
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {warnings: false},
      output: {comments: false},
      sourceMap: true
    })
  ]
};
```

**Comment by shankiesan** [comment]
Hmmm I'm having the same issue, but when using webpack straight up, rather than in Gulp. I've tried all the solutions listed here, but to no avail!

I'll report back here if I discover anything...

**Comment by alfonsoperez** [comment]
sourceMaps config parameter is now `false` by default 
https://gist.github.com/sokra/27b24881210b56bbaff7#gistcomment-1863573

**Comment by kisenka** [comment]
It doesn't work with `devtool: 'cheap-module-source-map'`
