### ISSUE TITLE
Is there a way to pass Webpack errors into Gulp-notify?

### ISSUE THREAD

**Issue by zellwk** [shama/webpack-stream#83]
as above

**Comment by shama** [comment]
Sorry I don't use gulp-notify. Could you provide more information? Is this because of an error in this package or just asking if I know how?

**Comment by zellwk** [comment]
Ah. I mean to ask if there's a way to tell Gulp about Webpack's error messages when it's in "watch mode". I was hoping to be able to catch these errors and somehow play a sound so I know I made an error. 

Does this make it clearer?

**Comment by mikemunsie** [comment]
Hey @zellwk, I use gulp-notify and you can display error messages using the stats object:

```
...
.pipe(webpack(require('../../webpack.config.js'), null, function(err, stats) {
  if (stats.compilation.errors.length > 0) {
    gulpNotify({
      title: "Webpack error",
      message: stats.compilation.errors[0].error
    });
  }
}))
```

There's a lot of info you can grab with the stats object, the filename, errors, and all sorts of other stuff. See: https://github.com/shama/webpack-stream/blob/master/index.js#L9

Cheers!

**Comment by zellwk** [comment]
@mikemunsie AWESOME! I'll check it out and get back to you in a week. love this! :)

**Comment by zellwk** [comment]
I used node-notifer instead of Gulp-notify and it worked. Here's my solution if anyone is interested: 

```
.pipe(webpackStream(config.webpack.options, webpack, (err, stats) => {
  if (stats.compilation.errors.length) {
        
    // Notifiers if errors
    notifier.notify({
      title: 'Webpack error',
      message: stats.compilation.errors[0].error,
      sound: 'Frog',
    });

    gutil.log(stats.compilation.errors[0]);
  }
}))
```
