### ISSUE TITLE
Version 2.2.0 failed to generate sourcemap.

### ISSUE THREAD

**Issue by singggum3b** [shama/webpack-stream#86]
I suppose it's related to the update , since version 2.1.1 worked properly with devtool = "source-map".
```javascript
return gulp.src("./src/js/**/*.js")
			.pipe(webpackgulp(assign({}, require("./webpack.config.js"), {
				entry: {
					"app.entry.js": "./src/js/app.entry.js"
				},
				watch: true,
				devtool: "source-map",
				output: {
					filename: "[name]",
					publicPath: "/js/",
					chunkFilename: "[id].[chunkhash].[name].js"
				},
				externals: {
					"jquery": "$",
					"react": "React",
					"react-dom": "ReactDOM",
					"react/addons": "React"
				},
				plugins: [
					// Linting Javascript files
					new OnCompilePlugin(function (params) {
						//gulp.run("lint");
					}),
					new webpack.optimize.CommonsChunkPlugin({
						async: true,
						minChunks: 2
					}),
					new webpack.optimize.DedupePlugin()
				]
			})))
			.pipe(gulp.dest("./build/dev/js/"));
```

the alert show that's there are source map generated , but there are no actual file output
```
Version: webpack 1.12.6
                          Asset     Size  Chunks             Chunk Names
                   app.entry.js  5.43 kB       0  [emitted]  app.entry.js
    1.3a2da803ac3411893152.1.js  69.1 kB       1  [emitted]  
               app.entry.js.map  6.02 kB       0  [emitted]  app.entry.js
1.3a2da803ac3411893152.1.js.map  93.4 kB       1  [emitted]  
[15:11:01] webpack is watching for changes
[15:11:02] Version: webpack 1.12.6
```

Its should be notify that version 2.1.1 work just fine.

**Comment by shama** [comment]
Hmm dang. If I don't get a fix soon for it I'll just revert it. Thanks for reporting!

/cc @OliverJAsh

**Comment by OliverJAsh** [comment]
You need to use [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps). Here's an example:

``` js
// gulpfile.babel.js

import gulp from 'gulp';
import uglify from 'gulp-uglify';
import sourcemaps from 'gulp-sourcemaps';
import rev from 'gulp-rev';
import webpackStream from 'webpack-stream';
import webpack from 'webpack';

gulp.task('build-app', () => (
    webpackStream({
        // watch: true,
        entry: {
            main: './public-src/js/main.js',
            vendor: ['virtual-dom', 'vdom-virtualize']
        },
        output: { filename: '[name]-bundle.js' },
        module: { loaders: [ { loader: 'babel-loader' } ] },
        devtool: 'source-map',
        plugins: [ new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor-bundle.js' }) ]
    })
        .pipe(sourcemaps.init())
        .pipe(uglify({ mangle: { toplevel: true }}))
        .pipe(rev())
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('./public/js'))
        .pipe(rev.manifest())
        .pipe(gulp.dest('./public/js'))
));
```

`gulp-sourcemap` is aware of the `sourceMap` property on the vinyl, which means it can handle transforms. Unfortunately this means you have to explicitly write it out using `.pipe(sourcemaps.write('.'))`.

**Comment by Zetoke** [comment]
What about, if I'm using gulp as task-runner, not builder?
I'm want use only webpack sourcemaps. And why I should using gulp-sourcemaps?

**Comment by singggum3b** [comment]
Since version 2.1.1 work just fine, i don't see why the need to complicating it by using another plugin for this.

**Comment by OliverJAsh** [comment]
@Zetoke I guess the simple change would be to detect if the config specifies `out`. If it does, then we can presume it's being used standalone, and we should emit the source map. If not, don't emit the source map and attach it to the vinyl instead.

I'm not sure if I'll have time to do this, but we definitely need a test for this!

**Comment by mikemagnusw** [comment]
I'm grateful to you guys for the work and as my morning disappears on being busily unproductive hunting down things like this, i'm also grateful this issue appears in google results.

What i might further like to know is how someone using gulp primarily as task runner, is supposed to infer that gulp-sourcemaps should be used (and with the write('.') syntax) to divert the map files being emitted by webpack from /dev/null back into the file stream, from "2.2.0 - Add support for source maps (@OliverJAsh)" in the release notes....

**Comment by OliverJAsh** [comment]
@mikemagnusw Please read my reply to @Zetoke in https://github.com/shama/webpack-stream/issues/86#issuecomment-160626453.

**Comment by mikemagnusw** [comment]
@OliverJAsh Thanks, i did; that's how i got stuff working again. My point is that that is not discoverable from the release notes for webpack-stream, especially without prior knowledge of the details of gulp's apparently special handling of map files, or exactly what "support for source map files" means in the context of webpack-stream, or how to restore functionality that Just Works™ in v2.1.x

I'm all for a proper and correct implementation but a note on using `.pipe(sourcemaps.init())` and `.pipe(sourcemaps.write('.'))` to restore something apparently broken would have been extremely useful and time-saving for more than myself.

**Comment by OliverJAsh** [comment]
We should mention in the docs that this has support for gulp-sourcemaps. Sorry it's caused you pain.

Who wants to do those two things, then?

**Comment by shama** [comment]
We should look into this more and see if we could make it more generic if possible otherwise revert the change and address it later.

I use webpack directly the times I do use source maps, so sorry if I'm being dense. But I don't think source maps should have a peer dependency to `gulp-sourcemaps` aka need some gulp plugin to work with source maps but maybe I'm not fully understanding things.

**Comment by mikemagnusw** [comment]
I suppose it all depends on whether one needs to do further processing in the gulp file stream, after webpack has done its thing. If not, it's probably reasonable that anything webpack emits is to be preserved as it was emitted.

In either case, perhaps the the behaviour of subsuming source map files should be opt-in, via a custom option to webpack-stream in the first parameter? This would avoid the additional dependency and confusion from changed/unexpected behaviour, while still enabling those who do want source map files to be handled in that way.

**Comment by OliverJAsh** [comment]
My solution: detect if `out` exists in the config. If it does, emit source map, if not, presume we're piping and use gulp-sourcemaps.

**Comment by mikemagnusw** [comment]
@OliverJAsh I'm not sure which `out` you're referring to. In any case, i for one am not using such an option in any gulp or webpack config.

**Comment by OliverJAsh** [comment]
Sorry, I mean `output`.

**Comment by mikemagnusw** [comment]
Ah! In that case i am using it in the webpack config, both `filename` and `publicPath`.

Would it be more appropriate to check for the presence of `output.filename` and if found, don't do anything special with the source maps?

**Comment by nervgh** [comment]
> Version 2.2.0 failed to generate sourcemap

same here
version `2.3.0` has same behaviour

**Comment by drinchev** [comment]
+1 ... I think using `gulp-sourcemaps` is not as bad as it sounds, but anyway it should definitely be better documented. This sounds like a breaking change and I also got some troubles finding that exactly `webpack-stream` broke with it's new version.

On my side if `webpack-stream` is gulp-oriented module it would be better if it is renamed `gulp-webpack-stream`. Because now it looks like you can't use it without gulp.

On the other hand I think it will be far better if the sourcemap feature is better documented.

Cheers!

**Comment by OliverJAsh** [comment]
Here is the proposed fix along with a test: #94.

Please can people here test this to make sure it works for everyones use cases?

gulp-sourcemaps is necessary if you want to pipe source maps through multiple tasks. I believe this will be built into Gulp in the next version.

**Comment by OliverJAsh** [comment]
Does someone want to raise another PR with the docs for this?

**Comment by shama** [comment]
While I appreciate what `gulp-sourcemaps` is trying to do, I don't think it's a good solution. It is effectively creating another spec for plugins to follow in order to support its behavior. People shouldn't need to know how gulp-sourcemaps works in order to use this library.

This library uses webpack to compile assets and then streams those assets. If you need to further handle those assets, such as manipulating source maps, you can pipe to another stream or library that does so. I've updated the readme with instructions on how to do so.

I've removed the special handling of source maps and will publish as a new major version to avoid further disruption. Thanks for bearing with me while I caught up on the use case.
