### ISSUE TITLE
2.2.0 breaks font awesome

### ISSUE THREAD

**Issue by mattlewis92** [shama/webpack-stream#87]
When upgrading from 2.1.1 to 2.2.0 any fonts loaded with webpack and passed through this library get broken with the console error:
```
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
OTS parsing error: incorrect file size in WOFF header
```

I'm guessing it's caused by this [commit](https://github.com/shama/webpack-stream/commit/41bca19968a8c0d69599e6c698f009e8f61f1584), there doesn't seem to be any check on the filetype so I suppose it's trying to apply the sourcemap to the font files.

I'll try and find the time later to put together a sample repo that demonstrates this.

**Comment by brev** [comment]
Duplicated. Downgrading back to 2.1.1 does fix. Thanks for filing @mattlewis92 .

**Comment by jeffijoe** [comment]
This breaks images as well.

**Comment by psi-4ward** [comment]
Thanks @brev downgrad solves it for me too

**Comment by shama** [comment]
Fixed on `3.0.0`.

**Comment by jv-PintoBobcat** [comment]
I'm still seeing this issue in 3.0.0.

**Comment by shama** [comment]
@jv-PintoBobcat Could you post an example that causes it to happen?

**Comment by fazo96** [comment]
I'm also experiencing this on 3.0.0.

If you want to reproduce on [my app](https://github.com/fazo96/ipfs-boards):

- set it up using [these istructions](https://github.com/fazo96/ipfs-boards/blob/master/CONTRIBUTING.md) but ignore everything related to go-ipfs and ipfs, they are not needed to reproduce this
- make sure you change the `webpack-stream` dependency in `package.json` to version `3.0.0` before launching `npm install` of course
- open the page at the webserver of `gulp serve`. You'll se the errors and the missing font awesome icons

I'm working around the issue by downgrading to 2.1.1 at the moment

**Comment by jv-PintoBobcat** [comment]
Please use @fazo96's app to reproduce this.  All of my apps that use this are proprietary projects from my company and aren't set up for public consumption at this time.  I'd have to create a mock project just to demonstrate this bug.

**Comment by fazo96** [comment]
@jv-PintoBobcat Fixed by 3.0.1 in my case :+1:

**Comment by opiepj** [comment]
Having the same issue with version 3.2.0

Loading font-awesome using:

```js
{test: /\.(woff|woff2|ttf|eot|svg|png|gif|jpg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url?limit=10000'}
```

And my output is
![image](https://cloud.githubusercontent.com/assets/7416676/15094358/d1e08f62-1455-11e6-8ac5-d41e9d2c554b.png)

**Comment by mattlewis92** [comment]
This is the webpack config I'm using successfully with font awesome + webpack stream (latest versions of both):
```
{
  test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
  loader: 'url?limit=10000&mimetype=application/font-woff'
}, {
  test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
  loader: 'file'
}
```
