### ISSUE TITLE
当gulp.src设置成src/js/**/*.js的时候，没有按照对应的目录生存代码，修改源码后即可，见截图

### ISSUE THREAD

**Issue by shendeganjue** [shama/webpack-stream#89]

**Comment by shama** [comment]
Sorry, I unfortunately can't read Chinese. I can only read English. :(

**Comment by shendeganjue** [comment]
![qq 20151202013453](https://cloud.githubusercontent.com/assets/6262382/11508861/dff41466-9895-11e5-9432-3a9c17ec1d62.png)
