### ISSUE TITLE
When I configure in gulp "gulp.src (['src/js/**/*.js'])," Finally, the generated js files in one directory, and then I modified the code, see screenshot:

### ISSUE THREAD

**Issue by shendeganjue** [shama/webpack-stream#90]
![qq 20151202013453](https://cloud.githubusercontent.com/assets/6262382/11509066/f288ff50-9896-11e5-9902-212bcaba7e6e.png)

**Comment by shama** [comment]
Sorry I'm not following, is this an issue related to this library `webpack-stream`? If so could you paste the code you're trying and the expected result?

**Comment by shendeganjue** [comment]
it is gulp-webpack.
![qq 20151202100825](https://cloud.githubusercontent.com/assets/6262382/11520279/f6d97864-98dc-11e5-89f2-6ade049c0bfe.png)

I've made a new adjustment.

**Comment by shendeganjue** [comment]
@shama  I've made a new adjustment, pictured above

**Comment by shama** [comment]
@shendeganjue Sorry I'm not sure what that code is and how it relates to `webpack-stream`.

**Comment by shendeganjue** [comment]
@shama The screenshots I upload your code error
![-1](https://cloud.githubusercontent.com/assets/6262382/11865423/e877fddc-a4de-11e5-8922-e45b01e0e61f.jpg)

**Comment by shendeganjue** [comment]
@shama I've made a new adjustment
![qq 20151217165425](https://cloud.githubusercontent.com/assets/6262382/11865449/0ed4aae8-a4df-11e5-843f-d487bfec0b07.png)

**Comment by shama** [comment]
Closing as I don't believe this is an issue with `webpack-stream`. The supplied code examples are not part of this library nor is the issue being explained.
