### ISSUE TITLE
[bug] Got format problem when using file-loader to copy images

### ISSUE THREAD

**Issue by minwe** [shama/webpack-stream#99]
**Type**: bug 

**What happens**: 

![2015-12-24 4 23 47](https://cloud.githubusercontent.com/assets/4370770/11991919/c073e216-aa5a-11e5-92bf-8bcb23ac59de.png)

I use `file-loader` to copy images, the images are copied, but can't open by both browser and Mac Finder, got format error as above.

**Steps to reproduce:**

1. `npm install gulp webpack-stream file-loader --save-dev`
2. `app.js`:

  ```js
  require('./path/to/some-image.jpg');
  ```

`gulpfile.js`

```js
var gulp = require('gulp');
var webpack = require('webpack-stream');

gulp.task('test', function() {
  return gulp.src('app.js')
    .pipe(webpack({
      output: {
        path: path.join(__dirname, 'dist'),
        filename: 'app.js',
      },
      module: {
        loaders: [
          {
            test: /\.jpe?g$|\.gif$|\.png|\.ico$/,
            loader: 'file?name=[name].[ext]'
          }
        ]
      }
    }))
    .pipe(gulp.dest('dist'));
});
```

3. `gulp test`
4. The image will be copied to `dist`, but can't open.

I tried webpack CLI, it works well. I think it caused by webpack-stream.

**Comment by minwe** [comment]
Sorry, it caused by `gulp-replace`.

**Comment by ianwith** [comment]
I have the same issue, but I did not use gulp-replace.
How do you solve that?
@minwe

**Comment by minwe** [comment]
@ianwith

I set `gulp-replace` [skipBinary](https://www.npmjs.com/package/gulp-replace#optionsskipbinary) option to `true`, then it works well..

You can try to comment gulp plugins one by one, and see after which the issue got resolved.

**Comment by ianwith** [comment]
I found this may caused by webpack-stream itself. When I upgrade webpack-stream from 2.1 to 3.1, the problem does not exist any more.

@minwe 
Thank you!
